import type { Quad } from '@rdfjs/types';

/**
 * Generates a report based on multiple input reports.
 * How the conflicts between multiple reports get resolved depend on the implemented algorithm.
 */
export interface ConflictResolver {
  /**
   * Resolves conflicts between reports.
   *
   * @param reports - Reports generated by an Evaluator, together with the corresponding policy.
   *
   * @returns A single report that aggregates the input reports into a single result.
   */
  resolve: (reports: { policy: Quad[]; report: Quad[] }[]) => Promise<Quad[]>;
}
