import type { Quad } from '@rdfjs/types';
import { AsyncHandler } from 'asynchronous-handlers';

export interface ConflictResolverArgs {
  /**
   * Reports generated by an Evaluator, together with the corresponding policy.
   */
  reports: { policy: Quad[]; report: Quad[] }[];
}

/**
 * Generates a report based on multiple input reports.
 * How the conflicts between multiple reports get resolved depend on the implemented algorithm.
 *
 * @returns A single report that aggregates the input reports into a single result.
 */
export abstract class ConflictResolver extends AsyncHandler<ConflictResolverArgs, Quad[]> {}
